# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb41e14dbdd8705f34c423e8ce01e16a086ab6de82ea3df7dedc3eef70770c8d304a7b5543221d40a9b85dd088f8719479ed876a3360224ffe82219ed5587aa

test:
  secret_key_base: 951270d32fd04e71e1f35178d2e2471beb05025d4ba7ce5b35f27e4845c34c31f3f0cc65c2ab4cfdfd7491a43a08fa5fbd2eb7269e0f45c1607597d9213b4b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
